---
- name: Config Nginx vhosts
  hosts: all
  become: yes

  vars:
    vhosts:
      - site1.local
      - site2.local
      - site3.local

  tasks:
     - name: Применить роль для каждого vhost
       include_role:
         name: nginx_vhost
       vars:
         vhost_name: "{{ item }}"
         vhost_root_base: "/var/www"
         vhost_port: 80
         vhost_extra_params: ""
       loop: "{{ vhosts }}"
